### ISSUE TITLE
Update coveralls due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-app-framework#543]
the Coveralls badge didn't make the move: https://coveralls.io/github/uPortal-Project/uportal-app-framework?branch=master

Preferably the person who owns the integration for this can update it.

**Comment by apetro** [comment]
repo now enrolled. https://coveralls.io/github/uPortal-Project/uportal-app-framework . I think it just needs a travis-ci build to run to bootstrap it.

**Comment by davidmsibley** [comment]
fixed!

**Comment by ChristianMurphy** [comment]
Thanks @apetro and @davidmsibley!
