### ISSUE TITLE
Update Appveyor due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-app-framework#544]
The original appveyor project didn't make the move to the new location, so in the meantime I set up a new project for the new name. However, there's a bunch of configuration in there that I wonder if we had set before the move.

Who owns the original appveyor integration? Can we use this new project without any problems or should we update the original project?

**Comment by ChristianMurphy** [comment]
I think @vertein set it up before.

It would be best to setup a uPortal-project account in appveyor that can be used organization wide.
Here are the instructions http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations
It needs an administrator to setup the webhook that links PRs to builds.

**Comment by apetro** [comment]
Eh. My read on those instructions is that we could set up an appveyor account for shared use, but that account would have its own username and password. So then we'd have to figure out how to securely share that password? Yuck. Let's not. Let's have an individual committer set this up again as themselves. All committers have Admin on this repo. Worst case from time to time the integration will need some ad-hoc attention -- I'd much rather that hassle than figure out how to share secrets.

**Comment by ChristianMurphy** [comment]
https://ci.appveyor.com/project/vertein/uportal-app-framework is now pointing to the new repo, thanks @vertein! :bow:
