### ISSUE TITLE
Update Greenkeeper due to repo move

### ISSUE THREAD

**Issue by davidmsibley** [uPortal-Project/uportal-app-framework#545]
Greenkeeper badge on the [readme](https://github.com/uPortal-Project/uportal-app-framework) doesn't like the new url. Can whoever owns the Greenkeeper integration update the project?

**Comment by apetro** [comment]
Enrolled the new repo at https://account.greenkeeper.io/account/uPortal-Project#repositories . I think it needs a Travis-CI run to bootstrap itself.

**Comment by davidmsibley** [comment]
fixed!

**Comment by ChristianMurphy** [comment]
Thanks @apetro and @davidmsibley!
