### ISSUE TITLE
Add deprecation notice to @uportal/uportal-app-framework

### ISSUE THREAD

**Issue by ChristianMurphy** [uPortal-Project/uportal-app-framework#547]
Add notice to `@uportal/uportal-app-framework` encouraging developers to use `@uportal/app-framework` instead.

ref: https://docs.npmjs.com/cli/deprecate

### Expected

```log
$ npm i @uportal/uportal-app-framework

npm WARN deprecated @uportal/uportal-app-framework@6.0.0: this package has been renamed, please use the @uportal/app-framework package.
+ @uportal/uportal-app-framework@6.0.0
added 5 packages in 0.815s
```

### Actual

``` log
$ npm i @uportal/uportal-app-framework

+ @uportal/uportal-app-framework@6.0.0
added 5 packages in 0.815s
```

### Why not unpublish `@uportal/uportal-app-framework`?

npm actively discourages unpublishing packages.

> WARNING
> It is generally considered bad behavior to remove versions of a library that others are depending on!
> Consider using the deprecate command instead, if your intent is to encourage users to upgrade.

ref: https://docs.npmjs.com/cli/unpublish

**Comment by davidmsibley** [comment]
Nice! I was just wondering if there was something we could do about that.  I'm cool with deprecating, I also wouldn't have anything against unpublishing in this case. The entry has been up for a short period of time, and was mainly a naming mistake by the publisher (me) rather than an upgrade.

**Comment by ChristianMurphy** [comment]
Either way works, if you decide to go the unpublish route, it is better to do that as soon as possible.

**Comment by ChristianMurphy** [comment]
Note that

> unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com.

ref: https://docs.npmjs.com/cli/unpublish#description

**Comment by apetro** [comment]
If we know anyone actually announced the mistaken naming coordinates, say on a list post, then I'd say deprecate. Otherwise, this isn't withdrawing something published so much as correcting a publication glitch, unpublish is fine, and anyone inconvenienced could rather immediately use the new name instead.

**Comment by ChristianMurphy** [comment]
The `@uportal/uportal-app-framework` package was referenced in a post.

ref: https://groups.google.com/a/apereo.org/d/msg/uportal-dev/4jWVfj8_xPo/4fsCHfu-AwAJ

**Comment by davidmsibley** [comment]
yup, that's fine, deprecating will do

**Comment by davidmsibley** [comment]
done
```
$ npm i @uportal/uportal-app-framework
npm WARN deprecated @uportal/uportal-app-framework@6.0.0: this package has been renamed, please use the @uportal/app-framework package.
```

**Comment by ChristianMurphy** [comment]
Thanks @davidmsibley! 🙇
