### ISSUE TITLE
Allow `chore:` as commit message type

### ISSUE THREAD

**Issue by apetro** [uPortal-Project/uportal-app-framework#648]
Came up in https://github.com/uPortal-Project/uportal-app-framework/pull/647#issuecomment-353095090 .

We [say we use](https://github.com/uPortal-Project/uportal-home/blob/master/.github/CONTRIBUTING.md#type) [AngularJS commit message conventions localization of Conventional Commits](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits). AngularJS conventions prescribe `chore:`. So our tooling should support `chore:`. 

(Technically, we say this in the context of `uPortal-home` rather than specifically here in the context of `uPortal-app-framework`, but I think there's at least a colorable argument that that's an oversight and if we wrote clearer `CONTRIBUTING.md` guidance here what it would say is we are trying to use AngularJS conventions.)

**Comment by ChristianMurphy** [comment]
See: marionebl/commitlint#146

Angular is changing their conventions to be different from Angular.js, `chore:` is no longer valid.
There is a guide based of the Angular.js conventional that we could switch to `config-conventional`.
The switch to `config-conventional` has already been made in `uPortal-home`, there is a PR to get the switch in to `uportal-app-framework` that is currently stalled. https://github.com/uPortal-Project/uportal-app-framework/pull/621

**Comment by ChristianMurphy** [comment]
resolved in https://github.com/uPortal-Project/uportal-app-framework/pull/621
