### ISSUE TITLE
Combine related automated version updates

### ISSUE THREAD

**Issue by ChristianMurphy** [uPortal-Project/uportal-app-framework#659]
One update from commit lint triggered 5 PRs
https://github.com/uPortal-Project/uportal-app-framework/pull/657, https://github.com/uPortal-Project/uportal-app-framework/pull/658, https://github.com/uPortal-Project/uportal-home/pull/767, https://github.com/uPortal-Project/uportal-home/pull/766, https://github.com/uPortal-Project/uportal-home/pull/765

GreenKeeper is considering adding support for grouping
https://github.com/greenkeeperio/greenkeeper/issues/514

[Renovate](https://renovateapp.com/) (a GreenKeeper competitor) [supports it today](https://renovateapp.com/docs/deep-dives/noise-reduction).

Is the irritation worth making the switch?

**Comment by ChristianMurphy** [comment]
Its also worth noting that renovate supports lockfile handling without needing to give it a repo auth token

**Comment by vertein** [comment]
I'm fine with leaving it as it is.

**Comment by ChristianMurphy** [comment]
That works, closing this issue
