### ISSUE TITLE
Appveyor : worth it?

### ISSUE THREAD

**Issue by apetro** [uPortal-Project/uportal-app-framework#728]
Seems like Appveyor is frequently false-failing in a way that's distracting rather than helpful.

![appveyor-ftl](https://user-images.githubusercontent.com/952283/37919809-9cd12706-30ea-11e8-851e-76798c8f26ea.png)

Something to be done to make it false-fail less? Time to give up on it?

It's mostly (but not entirely) conceptually redundant with Travis-CI, so maybe we wouldn't be giving up too much if we just turn it off.

**Comment by apetro** [comment]
I just now turned off the the requiredness of `continuous-integration/appveyor/pr` for the green merge button, which should at least reduce the indicator fatigue somewhat.

**Comment by ChristianMurphy** [comment]
> Something to be done to make it false-fail less?

https://github.com/appveyor/ci/blob/master/scripts/appveyor-retry.cmd may be able to help

> Time to give up on it?

I'd vote no.
uPortal-home has been adopted on Windows elsewhere, having continuous integration on Windows gives some level of assurances the uPortal home will continue to work for that adopter.
Those assurances are brought with, what is IMO, a low level of effort on the part of developers.

**Comment by ChristianMurphy** [comment]
AppVeyor has been switched off
